Gio/release with static analysis (#110)
* Fix issue missing tree_sitter_python

* Explicitly make FORK the multiprocessing option to choose

This is because in the MacOS release build (at least) I keep seeing errors like:
```
Error: No such option: --multiprocessing-fork
Usage: main [OPTIONS] COMMAND [ARGS]...
Try 'main --help' for help.

Error: No such option: -B
Usage: main [OPTIONS] COMMAND [ARGS]...
Try 'main --help' for help.
```

Which are from instantiating new processes, for sure.
This SO question: https://stackoverflow.com/questions/67999589/multiprocessing-with-pool-throws-error-on-m1-macbook
Indicates it might be the way it creates new processes and suggests using "fork" explicitly.
We're giving that a go.