Fix path_fixes in upload payload (#103)
Recently testing the CLI with the new upload endpoint I had the following error (when trying to upload the CLI itself)
```
TypeError: keys must be str, int, float, bool or None, not PosixPath
Error: Process completed with exit code 1.
```

After some digging I found the keys in question
```
Finding the PosixPath
Key languages/languages.c is PosixPath. Origin: .path_fixes.value[languages/languages.c]
Key tests/data/files_to_fix_examples/sample.cpp is PosixPath. Origin: .path_fixes.value[tests/data/files_to_fix_examples/sample.cpp]
Key tests/data/files_to_fix_examples/sample.go is PosixPath. Origin: .path_fixes.value[tests/data/files_to_fix_examples/sample.go]
Key tests/data/files_to_fix_examples/sample.kt is PosixPath. Origin: .path_fixes.value[tests/data/files_to_fix_examples/sample.kt]
Key tests/data/files_to_fix_examples/sample.php is PosixPath. Origin: .path_fixes.value[tests/data/files_to_fix_examples/sample.php]
Finding the PosixPath ================ END
```

They come from the path_fixes, which are of class Path, but need to be strings.
To solve this we simply cast them to string while building the payload.

The reason this was not picked up in the unit tests before is that we were already passing strings, not Path as it should be.