Improve the error message when no token is found (#116)
* Improve the error message when no token is found

The current error message from when the codecov token is not found is `AttributeError: 'NoneType' object has no attribute 'hex'`
That's obviously not very useful for users.

These changes implement a `get_token_header_or_fail` function that get's the token header or fails with an exeption saying "Codecov token not found." hopefully more descriptive to our users.

* Don't raise error on legacy.

Legacy upload endpoint has tokenless uploads, so it's not a good idea to raise errors.
We're trusting that click won't let the token be anything other than UUID, so it's either that or None.
In the case of None we send an empty token in the headers.